spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipeManager?createDatabaseIfNotExist=true
    username: root
    password: root
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
