#h2
spring:
  h2:
    console:
      enable: true
      path: /h2
#datasource
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/recipe-manager;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: recipe
    password:
# jpa
  jpa:
    showSql: true